language: python

services:
  - docker
  - redis-server
  - mongodb

env:
  - DOCKER_COMPOSE_VERSION: 2.0

before_install:
  - sudo apt-get update
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine
  - docker-compose --version
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose --version

#  - sudo rm /usr/local/bin/docker-compose
#  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
#  - chmod +x docker-compose
#  - sudo mv docker-compose /usr/local/bin

install:
  - docker-compose build
  - docker-compose up -d

before_script:
  - curl -X POST http://localhost:2000/put -i -d 'key="hello"&value=world'

script:
  - python TestCase.py

after_script:
  - docker-compose down